[profile.default]
src = 'src'
out = 'out'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@zk-kit/=node_modules/@zk-kit/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
libraries = [
    "@zk-kit/incremental-merkle-tree.sol/Hashes.sol:PoseidonT3:0x1234000000000000000000000000000000000000",
    "@zk-kit/incremental-merkle-tree.sol/IncrementalBinaryTree.sol:IncrementalBinaryTree:0x5678000000000000000000000000000000000000",
    "src/base/Pairing.sol:Pairing:0xabcd000000000000000000000000000000000000"
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config